---
# tasks file for arch_provision

- name: Install base packages
  import_role:
    name: arch_provision/subtasks/pacstrap
  tags:
    - base_install
  vars:
    packages:
      # Base system
      - base
      - linux
      - linux-firmware
      # Necessary extras
      - e2fsprogs
      - exfat-utils
      - iproute2
      - dhcpcd
      - neovim
      - nano
      - grub
      - efibootmgr
      - networkmanager
      - man-db
      - man-pages
      - sudo
      - openssh
      - tmux
      - git
      - xdg-user-dirs

- import_role:
    name: arch_provision/subtasks/genfstab
  tags:
    - base_install

- import_role:
    name: arch_provision/subtasks/locale
  tags:
    - base_install

- import_role:
    name: arch_provision/subtasks/hostname
  tags:
    - base_install

- import_role:
    name: arch_provision/subtasks/copy_keys
  tags:
    - base_install

- name: symlink vim to nvim
  file:
    state: link
    src: /usr/bin/nvim
    dest: /usr/bin/vim

- name: symlink vi to nvim
  file:
    state: link
    src: /usr/bin/nvim
    dest: /usr/bin/vi

- name: Copy /etc/issue replacement
  copy:
    dest: "{{ rootfs_mountpoint }}/etc/issue"
    src: "../files/issue"
  tags:
    - base_install

- name: Enable services on installed system
  command: arch-chroot {{ rootfs_mountpoint | quote }}
    systemctl enable {{ item | quote }}
  loop:
    - sshd
    - NetworkManager
    # - rc-local
  tags:
    - base_install