---
# tasks file for arch_provision

- name: Install base packages
  import_role:
    name: arch_provision/subtasks/pacstrap
  tags:
    - base_install
  vars:
    packages:
      # Base system
      - base
      - linux
      - linux-firmware
      # Drivers and bootloader
      - e2fsprogs
      - exfat-utils
      - iproute2
      - dhcpcd
      - grub
      - efibootmgr
      - networkmanager
      - man-db
      - man-pages
      - sudo
      - openssh
      # Necessary extras
      - fakeroot
      - neovim
      - nano
      - tmux
      - git
      - xdg-user-dirs
      - python
      - htop
      ## Needed to install aur helper later
      - base-devel

- name: Install additional specified packages
  import_role: 
    name: arch_provision/subtasks/pacstrap
  tags:
    - base_install
  vars:
    packages: "{{ bootstrap_packages }}"

- import_role:
    name: arch_provision/subtasks/genfstab
  tags:
    - base_install

- import_role:
    name: arch_provision/subtasks/locale
  tags:
    - base_install

- import_role:
    name: arch_provision/subtasks/hostname
  tags:
    - base_install

- import_role:
    name: arch_provision/subtasks/copy_keys
  tags:
    - base_install

- name: Copy /etc/issue replacement
  copy:
    dest: "{{ rootfs_mountpoint }}/etc/issue"
    src: "../files/issue"
  tags:
    - base_install

- name: Enable services on installed system
  command: arch-chroot {{ rootfs_mountpoint | quote }}
    systemctl enable {{ item | quote }}
  loop:
    - sshd
    - NetworkManager
  tags:
    - base_install


- import_role:
    name: arch_provision/subtasks/mkinitcpio
  tags:
    - base_install