---
# tasks file for driver_amdgpu

- name: Install packages
  pacman:
    name:
      - mesa
      - xf86-video-amdgpu
      - vulkan-radeon
      - libva-mesa-driver
      - nvtop

- name: Install 32-bit packages
  when: "amdgpu_32bit_support == true"
  pacman:
    name:
      - lib32-mesa
      - lib32-vulkan-radeon