---
# tasks file for display_manager

- debug:
    var: display_manager

- name: Jump to subtask to install Display Manager
  import_tasks: sddm.yml
  when: "display_manager == 'sddm'"

- name: Jump to subtask to install Display Manager
  import_tasks: lightdm.yml
  when: "display_manager == 'lightdm'"