---
# tasks file for sudo

- name: Add sudo group configuration to the sudoers file
  community.general.sudoers:
    name: sudo_group
    group: "{{ sudo_group }}"
    commands: ALL
    nopassword: false
    runas: ALL:ALL
    validation: required
- name: Let ansible user have sudo access without typing in password
  community.general.sudoers:
    name: ansible
    user: "{{ user_control_name }}"
    commands: ALL
    nopassword: true
    runas: ALL:ALL
    validation: required