---
# tasks file for postinstall (as root)

- name: symlink vim to nvim
  file:
    state: link
    src: "/usr/bin/nvim"
    dest: "/usr/bin/vim"

- name: symlink vi to nvim
  file:
    state: link
    src: "/usr/bin/nvim"
    dest: "/usr/bin/vi"

- import_role:
    name: postinstall/subtasks/users
  tags:
    - users
- import_role:
    name: postinstall/subtasks/sudo
  tags:
    - sudo
- import_role:
    name: postinstall/subtasks/ssh_config
  tags:
    - ssh_config