# Variables for all hosts
## Ansible Configuration
ansible_user: ansible

## General Configuration
users:
- name: brady
  sudo: true
  admin: true
  generate_ssh_key: true
  password_hash: "{{ 'password' | password_hash('sha512') }}"
  comment: "Brady O'Leary"
  groups:
    - sudo
    - sys
    - wheel
    - adm
    - uucp
    - network

user_groups:
- sudo
