# Variables for all hosts
## Ansible Configuration
ansible_user: ansible

## Global Variables to be used elsewhere
global_users:
- name: brady
  sudo: true
  admin: true
  generate_ssh_key: true
  password_hash: "{{ 'password' | password_hash('sha512') }}"
  comment: "Brady O'Leary"
  groups:
    - sudo
    - sys
    - wheel
    - adm
    - uucp
    - network
## General Configuration
### Override this to add more users
users: "{{ global_users }}"

user_groups:
- sudo
