---
# tasks file for x11

- name: Install the xorg packages
  pacman:
    name:
      - xorg
      - xorg-apps
      - xorg-fonts
      # Only needed for my demo
      # - xorg-twm
      # - xorg-xinit
      # - xorg-xclock
      # - xterm
      # - xorg-xeyes

- name: Install xinit script
  when: "x11_xinit == true"
  import_tasks: xinit.yml