---
# tasks file for lightdm

- name: Install lightdm packages
  pacman:
    name:
      - lightdm
      - xorg-server-xephyr
      - accountsservice
      - light-locker

- name: Install and configure greeter
  import_tasks: greeter.yml

- name: Enable systemd service
  systemd:
    enabled: true
    state: started
    name: lightdm.service

- name: Hide control user
  lineinfile:
    path: "/etc/lightdm/users.conf"
    backup: true
    regexp: "^hidden-users=([a-z0-9 ]*)"
    backrefs: true
    line: 'hidden-users=\1 {{ ansible_user }}'

- name: Configure autologin
  when: "lightdm_autologin == true"
  import_tasks: autologin.yml