all:
  hosts:
    172.31.1.233:
      

  children:
    ## System Type Groups
    vm:
      hosts:
        172.31.1.233:
          vm: true
          vm_backend: kvm
    graphical:
      hosts:
        172.31.1.233:
          display_server: xorg
          desktop_environment: kde
          display_manager: sddm