all:
  hosts:
    # 192.168.122.127:
    #   hostname: archtest

  children:
    provision:
      hosts:
        192.168.122.127:
          hostname: archtest
          partition: true
          timezone: "US/Eastern"
          partition_options:
            disk: /dev/vda
            # swap: true
            # swap_size: 8
            # separate_home: true
            # root_size: 32
            # encrypt: true
          disksetup_flow: singlepart