# Main playbook
- name: Install Base System
  hosts: provision
  remote_user: root
  vars:
    # temporary
    rootfs_mountpoint: /mnt
  tags:
    - never
    - bootstrap
  tasks:
    # - import_role:
    #     name: disk_setup
    - import_role:
        name: arch_provision
    - import_role:
        name: bootloader
- name: List facts for testing
  hosts: postinstall
  remote_user: root
  tags:
    - postinstall
  tasks:
    - import_role:
        name: postinstall
- name: General Configuration
  hosts: all
  tags:
    - config
  tasks:
    - debug:
        msg: hellorld!


# - name: Run updates
#   hosts: all
#   tags:
#     - update
#   tasks: