# Main playbook
- name: Install Base System
  hosts: provision
  remote_user: root
  vars:
    # temporary
    rootfs_mountpoint: /mnt
  tags:
    - never
    - bootstrap
  tasks:
    - import_role:
        name: disk_setup
    - import_role:
        name: arch_provision
    - import_role:
        name: bootloader

- name: List facts for testing
  hosts: postinstall
  remote_user: root
  tags:
    - postinstall
  tasks:
    - import_role:
        name: postinstall

- name: VM Guest Additions
  hosts: vm
  become: true
  tags:
    - hardware
    - vm
  tasks:
    - import_role:
        name: vmguest
      when: vm == true

- name: Graphical System Configuration
  hosts: graphical
  become: true
  tags:
    - graphical
  tasks:
    - import_role:
        name: display_server
    - import_role:
        name: display_manager
    - import_role:
        name: desktop_environment


# - name: Run updates
#   hosts: all
#   tags:
#     - update
#   tasks: