# Main playbook

- name: VM Guest Additions
  hosts: vm
  become: true
  tags:
    - hardware
    - vm
  tasks:
    - import_role:
        name: vmguest
      when: vm == true

- name: Graphical System Configuration
  hosts: graphical
  become: true
  tags:
    - graphical
  roles:
    - display_server
    - display_manager
    - desktop_environment


# - name: Run updates
#   hosts: all
#   tags:
#     - update
#   tasks: