# Main playbook
- name: General configuration
  hosts: all
  become: true
  tags:
    - configure
  roles: 
    - aur_helper
    - network_manager_config
    - avahi

- name: Configure Users
  hosts: all
  become: true
  tags:
    - users
  roles: 
    - users

- name: VM Guest Additions
  hosts: vm
  become: true
  tags:
    - hardware
    - vm
  tasks:
    - import_role:
        name: vmguest
      when: vm == true

- name: Graphical System Configuration
  hosts: graphical
  become: true
  tags:
    - graphical
  roles:
    - meta_display_server
    - meta_display_manager
    - meta_desktop_environment
    - pulseaudio

- name: Configure Multimedia system
  hosts: kodi
  become: true
  tags:
    - kodi
  roles:
    - driver_amdgpu
    - kodi
    - pulseaudio
    - meta_display_server
    - meta_display_manager
    - meta_desktop_environment
    - meta_games
    - meta_web_browser

- name: Run updates
  hosts: all
  become: true
  tags:
    - update
  roles:
    - update