# Main playbook
- name: Install Base System
  hosts: provision
  remote_user: root
  vars:
    # temporary
    rootfs_mountpoint: /mnt
  tags:
    - never
    - bootstrap
  tasks:
    # - import_role:
    #     name: disk_setup
    - import_role:
        name: arch_provision