# Main playbook

- name: VM Guest Additions
  hosts: vm
  become: true
  tags:
    - hardware
    - vm
  tasks:
    - import_role:
        name: vmguest
      when: vm == true

- name: Graphical System Configuration
  hosts: graphical
  become: true
  tags:
    - graphical
  roles:
    - meta_display_server
    - meta_display_manager
    - meta_desktop_environment

- name: General configuration
  hosts: all
  become: true
  tags:
    - configure
  roles: 
    - aur_helper
    - users
    - network_manager_config
    - avahi

- name: Configure Multimedia system
  hosts: kodi
  become: true
  tags:
    - kodi
  roles:
    - kodi
    - pulseaudio
    - meta_display_server
    - meta_display_manager
    - meta_desktop_environment

# - name: Run updates
#   hosts: all
#   tags:
#     - update
#   tasks: