---
# tasks file for update
# - name: Copy update script
#   copy:
#     src: auto_update_script.sh
#     dest: "{{ global_bin_directory }}"
#     mode: "0644"
- name: Run update script
  script: auto_update_script.sh
